import fs from "fs";
import path from "path";
import type {
  ContentPageData,
  Product,
  ProductsPageData,
  SiteConfig,
  StorePageData,
} from "./types";
import siteJson from "@/public/data/site.json";
import productsJson from "@/public/data/products.json";
import pagesJson from "@/public/data/pages.json";

const pages = pagesJson as Record<string, ContentPageData>;

const STORES_DIR = path.join(process.cwd(), "public", "data", "stores");

function readStoreFile(slug: string): StorePageData | null {
  const filePath = path.join(STORES_DIR, `${slug}.json`);
  if (!fs.existsSync(filePath)) return null;
  try {
    const raw = fs.readFileSync(filePath, "utf8");
    return JSON.parse(raw) as StorePageData;
  } catch {
    return null;
  }
}

export const CONTENT_PAGE_SLUGS = [
  "about",
  "terms",
  "privacy",
  "contact",
  "blogs",
  "join",
  "forgot-password",
  "categories",
  "stores",
] as const;

export type ContentPageSlug = (typeof CONTENT_PAGE_SLUGS)[number];

export function getContentPage(slug: string): ContentPageData | null {
  return pages[slug] ?? null;
}

export function getCategoryPage(slug: string): ContentPageData | null {
  const categories = pages.categories;
  if (!categories?.categoryList) return null;
  const cat = categories.categoryList.find((c) => c.slug === slug);
  if (!cat) return null;
  return {
    title: cat.title,
    lead: cat.description,
    sections: [
      {
        heading: "Browse this category",
        body: "Products tagged for this category are listed below.",
      },
    ],
  };
}

function normalizeCategory(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getAllCategorySlugs(): string[] {
  return pages.categories?.categoryList?.map((cat) => cat.slug) ?? [];
}

export function getCategoryProducts(slug: string): Product[] {
  const target = normalizeCategory(slug);
  return (productsJson as ProductsPageData).items.filter((product) => {
    if (!product.category) return false;
    return normalizeCategory(product.category) === target;
  });
}

export function getBlogPost(slug: string): ContentPageData | null {
  const blogs = pages.blogs;
  const post = blogs?.posts?.find((p) => p.slug === slug);
  if (!post) return null;
  return {
    title: post.title,
    lead: post.excerpt,
    sections: [
      {
        heading: "Published",
        body: post.date,
      },
      {
        heading: "Article",
        body: "This is a placeholder blog article. Replace body copy in public/data/pages.json or connect a CMS for full posts.",
      },
    ],
  };
}

export function getSiteConfig(): SiteConfig {
  return siteJson as SiteConfig;
}

export function getProductsData(): ProductsPageData {
  return productsJson as ProductsPageData;
}

/** Load store JSON generated by `npm run import:cms` (public/data/stores/[slug].json). */
export function getStoreBySlug(slug: string): StorePageData | null {
  return readStoreFile(slug);
}

/** All store slugs present in public/data/stores/*.json */
export function getAllStoreSlugs(): string[] {
  if (!fs.existsSync(STORES_DIR)) return [];
  return fs
    .readdirSync(STORES_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort();
}
